# Wine_Prediction_with_LR_Using_LDA

**Note:**
- In this experiment, we will perform several operations on a CSV file using the NumPy, Pandas, Matplotlib, Seaborn, and SKLearn libraries.
- We are going to perform the LDA technique on the Dataset.
- Our primary focus will be on key operations commonly used in these libraries for building Logistic Regression models.
- The following operations will be conducted on the CSV file:

   - Importing the necessary libraries.
   - Loading the dataset for the experiment.
   - Understanding the data contained in the file.
   - Performing data cleaning and visualisation operations.
   - Preparing the data for further processing within the Data Science Life Cycle.
   - Conducting Exploratory Data Analysis (EDA) on the processed data.
   - Building predictive models using the EDA-processed data.
   - Performing model evaluations.

**Experiment Link** -->https://colab.research.google.com/drive/1fFFmwGjr4ZvuUSeYH1KHBHasMk4kMgsd?usp=sharing

### STEP 1. Problem statement:-

### STEP 2.Importing the necessary libraries.

In [1]:
# Importing the required libraries.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### STEP 3.Loading the Dataset into the Environment.

In [2]:
from sklearn.datasets import load_wine

In [3]:
# Loading the dataset.
dataset = load_wine()

In [4]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [5]:
# Understanding the dataset.
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: float64(13)
memory usage: 18.2 KB

In [7]:
df['Target'] = dataset.target

In [8]:
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,Target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [9]:
df['Target'].unique()

array([0, 1, 2])

In [10]:
df.shape

(178, 14)

### STEP 4. Data Cleaning Operation performed on the dataset.

In [11]:
# checking for null values.
df.isnull().sum().sum()

np.int64(0)

In [12]:
# Checking for Duplicate Values.
df.duplicated().sum()

np.int64(0)

### STEP 5. Divide the dataset into features (x) and the target variable (y) for training the model.

In [13]:
x = df.drop('Target',axis=1)
y = df['Target']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train , x_test , y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=3)

In [16]:
x_train.shape

(142, 13)

In [17]:
y_train.shape

(142,)

### STEP 6.Feature Engineering
- For Encoding, Scaling, and feature creation.

**LDA -** Linear DiscriminantAnalysis

- It is a supervised machine learning technique.
- Its main goal is to maximise class separability.
- LDA works by finding a linear combination of features that best separates the classes.

**Process** -
- Apply standardisation on the x dataframe.
- selecting the n components for creating the LDA.


- To find the number of components required for LDA, use the formula.
- n_components = min(no.of features,no.of classes-1).
- EX:-

    - number of features = 14
    - number of classes = 03
    - min(14,3-1) => min(14,2)
    - 9 is the minimum, so we will select 9 components.

In [18]:
# STEP 1- Standardize the data
from sklearn.preprocessing import StandardScaler

In [19]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

- We do not use fit on x_test because we don't want  do not use fit on x_test because we don't to recalculate the mean and sd.

In [20]:
x_train.std()

np.float64(1.0)

In [21]:
x_test.std()

np.float64(0.9802407679618195)

In [22]:
pd.DataFrame(x_train)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1.083561,-0.463937,0.886065,-1.313536,0.103089,1.595769,1.554614,-1.560355,0.221915,0.124721,-0.302114,1.349085,1.158421
1,-0.788315,-1.090776,-1.573102,0.029400,-1.507862,-0.281852,0.013221,-0.759015,-0.909019,-0.194193,0.782823,1.236653,-0.705274
2,0.711666,-0.664177,0.041874,-0.116571,0.453296,0.953425,1.189027,-1.159685,0.650299,0.749792,0.647206,0.393413,2.496460
3,0.438942,0.119372,0.005170,0.146177,-0.737407,-1.451248,-1.468888,0.042324,-1.594434,0.197008,-1.115817,-0.182801,0.154893
4,1.480250,-0.577116,0.372209,-1.255148,0.873544,1.628710,1.386642,-0.198078,0.684570,0.686010,0.466383,0.351251,2.289382
...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,-0.094109,1.198928,1.106289,-0.262543,0.173130,0.212259,0.418330,-0.919283,0.701706,-0.270733,0.375971,1.292869,0.123035
138,1.517440,-0.620647,0.298801,-1.138371,1.924164,0.854603,1.060578,-0.678881,1.232902,0.214017,0.421177,1.855029,1.062847
139,-0.156092,0.493734,0.188689,0.146177,0.313213,-1.615951,-0.757476,-0.999417,-1.268862,0.111964,-0.934994,-1.658471,-0.641558
140,0.129029,-0.455231,1.473329,1.751862,1.153709,-0.133619,-0.698192,-0.839149,-0.017980,0.834836,-1.522668,-1.784957,-0.976068
141,-0.937073,-0.603235,-0.839022,-0.145766,-1.367779,-1.039489,0.042863,0.042324,0.101968,-0.738473,0.240354,0.800979,-0.705274

In [23]:
 # Apply LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [24]:
LDA = LinearDiscriminantAnalysis(n_components=2)
x_train = LDA.fit_transform(x_train,y_train)
x_test = LDA.transform(x_test)

In [25]:
x_train.shape

(142, 2)

In [26]:
x_test.shape

(36, 2)

### STEP 7.Model Selection & Training: Choose algorithms based on problem type.

In [27]:
# Train the model.
from sklearn.linear_model import LogisticRegression

In [28]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [29]:
# Predicting the values with test data.
model_pred = model.predict(x_test)

In [30]:
new_df = pd.DataFrame({'Actual':y_test,'Predicted':model_pred})
new_df.head()

     Actual  Predicted
40        0          0
53        0          0
34        0          0
109       1          1
159       2          2

### STEP 8: Model Evaluation  
- Assessing the performance of the model based on various parameters.

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [32]:
accuracy_score(y_test,model_pred)

1.0

In [33]:
confusion_matrix(y_test,model_pred)

array([[15,  0,  0],
       [ 0, 14,  0],
       [ 0,  0,  7]])

- After building the ML model using the PCA data, we evaluated it and achieved " 100 % accuracy ".